name: Deploy React App to cPanel

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get lates code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build the React app
        run: |
          cd client
          npm run build

      - name: Copy files to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          server: server.hglk.link           # Your FTP host (check in cPanel)
          username: taprodev
          password: sxTqoE|QhTzq
          local-dir: client/build
          server-dir: /home/taprodev/qa.taprodevpos.com/
          protocol: ftps                        # use 'ftp' if your host doesn’t support FTPS
          port: 21
          log-level: standard
